/**
 * stremio_bridge.js — Main-world bridge for Stremio Web ("Play in MPV")
 * Part of: biraj-mpv-conf | github.com/Biraj2004/biraj-mpv-conf
 *
 * Runs directly in Stremio Web's JavaScript execution environment (MAIN world)
 * to intercept stream URLs generated by Stremio's internal handlers when
 * copying stream links, enabling instant handoff to local MPV without
 * asking for clipboard permissions.
 *
 * Security:
 *  - Sandboxed communication via window.postMessage with strict origin and nonce checks.
 *  - Validates all captured URLs before dispatching.
 *  - Zero eval, zero inline script strings, zero external network requests.
 */

(function () {
  'use strict';

  if (window.__PLAY_IN_MPV_BRIDGE_ACTIVE__) return;
  window.__PLAY_IN_MPV_BRIDGE_ACTIVE__ = true;

  // Hook navigator.clipboard.writeText in the page's execution context
  if (navigator.clipboard && typeof navigator.clipboard.writeText === 'function') {
    const originalWriteText = navigator.clipboard.writeText.bind(navigator.clipboard);

    navigator.clipboard.writeText = function (text) {
      const nonce = document.documentElement.getAttribute('data-mpv-nonce');
      const isArmed = !!nonce;

      if (nonce) {
        document.documentElement.removeAttribute('data-mpv-nonce');
      }

      if (typeof text === 'string') {
        const trimmed = text.trim();
        const isStreamUrl = /^(https?|http|magnet):/i.test(trimmed);

        if (isArmed && isStreamUrl) {
          window.postMessage({
            source: 'PLAY_IN_MPV_BRIDGE',
            type: 'CAPTURED_STREAM_URL',
            nonce: nonce,
            url: trimmed
          }, '*');
        }
      }

      // Always allow native clipboard write to proceed so user clipboard still works
      return originalWriteText(text).catch(() => {});
    };
  }
})();
