## Mouse
MBTN_LEFT_DBL    cycle fullscreen
MBTN_LEFT        ignore
MBTN_RIGHT       script-binding select/context-menu

## Media keys
PLAY             cycle pause
PAUSE            cycle pause
PLAYPAUSE        cycle pause

NEXT             playlist-next
PREV             playlist-prev
MUTE             osd-msg cycle mute
VOLUME_UP        osd-msg add volume  5
VOLUME_DOWN      osd-msg add volume -5

FORWARD          osd-msg-bar seek  15 relative+exact
REWIND           osd-msg-bar seek -15 relative+exact

CLOSE_WIN        quit

## Arrows
RIGHT            osd-msg-bar seek  5 relative+exact
LEFT             osd-msg-bar seek -5 relative+exact
UP               osd-msg add volume 5
DOWN             osd-msg add volume -5

## Keyboard - essentials only
SPACE            cycle pause

n                playlist-next
p                playlist-prev
k                script-binding sort_playlist/sort-playlist
i                script-binding stats/display-stats-toggle
l                script-binding hdr_badge/toggle-hdr-badge

# Screenshot
s                screenshot

# VLC-style track cycling
b                cycle audio
v                cycle sub

m                osd-msg cycle mute

.                frame-step
,                frame-back-step

f                cycle fullscreen
ESC              set fullscreen no

Ctrl+o           script-binding open_file/open
Ctrl+s           script-binding open_file/add_subtitle
Ctrl+a           script-binding open_file/add_audio

q                quit

HOME             seek 0 absolute

TAB              script-binding modernz/visibility
g-m              script-binding select/menu

# Image viewer keybinds
WHEEL_UP         {image} script-binding positioning/cursor-centric-zoom  0.1
WHEEL_DOWN       {image} script-binding positioning/cursor-centric-zoom -0.1
0                {image} no-osd set video-align-y 0; no-osd set video-align-x 0

# Audio effects & night mode
y                cycle-values af "lavfi=[dynaudnorm=f=75:g=25:p=0.55]" ""

# Stream quality & profile selection
Ctrl+y           cycle-values ytdl-format "bestvideo[height<=?720]+bestaudio/best[height<=?720]/best" "bestvideo[height<=?1080]+bestaudio/best[height<=?1080]/best" "bestvideo[height<=?1440]+bestaudio/best[height<=?1440]/best" "bestvideo[height<=?1440]+bestaudio/bestvideo[height<=?1080]+bestaudio/bestvideo[height<=?720]+bestaudio/bestvideo+bestaudio/best[height<=?1440]/best"
Alt+p           script-binding select/select-profile
F9               script-binding select/select-profile