@echo off
setlocal EnableDelayedExpansion
title Stremio Setup To Play In MPV - by Biraj2004
cd /d "%~dp0"

:: =======================================================================================================
:: GitHub      : https://github.com/Biraj2004
:: Developer   : Biraj
:: Description : Configures Stremio to add MPV player integration ("Play in MPV").
::                - Automatically locates MPV (mpv.exe / mpvnet.exe) across PATH, Scoop, and standard paths.
::                - Detects active Stremio processes to prevent locked file conflicts during patching.
::                - Injects the MPV configuration and robust launch handler into Stremio's server.js.
::                - Automatically creates timestamped backups (.backup_YYYYMMDD_HHMMSS) before modifying.
::                - Re-running this script is SAFE: existing up-to-date configurations are skipped.
:: =======================================================================================================

echo =======================================================================================================
echo                                  STREMIO SETUP TO PLAY IN MPV
echo                       Developed by : Biraj
echo                       GitHub       : https://github.com/Biraj2004
echo =======================================================================================================
echo.
echo [INFO] Working Folder   : %CD%
echo [INFO] Target           : Stremio server.js (External Player Configuration)
echo [INFO] Action           : Add "Play in MPV" option next to "Play in VLC" in player menu
echo [INFO] Scope            : Local Stremio installation(s)
echo [INFO] Safety           : Full timestamped backup (.backup_*) created before modifying files
echo.
echo =======================================================================================================
echo  WARNING: This will configure Stremio to add MPV as an external player option.
echo =======================================================================================================
echo.
set "CONFIRM="
set /p CONFIRM=Type Y and press Enter to proceed, or N to cancel : 

if /i "%CONFIRM%"=="Y" goto :PROCEED
if /i "%CONFIRM%"=="YES" goto :PROCEED

echo.
echo [CANCELLED] Setup execution cancelled. No files or settings were modified. Exiting safely.
echo.
pause
endlocal
exit /b 0

:PROCEED
echo.
echo [PROCESSING] Checking system prerequisites and locating MPV...
echo =======================================================================================================

REM ----------------------------------------------------------------
REM  Helper vars (must be set OUTSIDE any parenthesized block -
REM  "ProgramFiles(x86)" contains a ")" which breaks cmd's block
REM  parser if used directly inside an if/for block).
REM ----------------------------------------------------------------
set "PF=%ProgramFiles%"
set "PF86=%ProgramFiles(x86)%"
set "LAD=%LocalAppData%"
set "UP=%UserProfile%"

REM ================================================================
REM  STEP 1: Locate mpv on this system
REM ================================================================
set "MPV_PATH="

REM 1a. Allow passing a path manually, e.g.:
REM     Win_Setup_Stremio_To_Play_In_MPV.bat "D:\Apps\mpv\mpv.exe"
if not "%~1"=="" if exist "%~1" set "MPV_PATH=%~1"

REM 1b. Check the system PATH
if not defined MPV_PATH (
    where mpv.exe >nul 2>&1
    if not errorlevel 1 for /f "delims=" %%P in ('where mpv.exe') do if not defined MPV_PATH set "MPV_PATH=%%P"
)
if not defined MPV_PATH (
    where mpvnet.exe >nul 2>&1
    if not errorlevel 1 for /f "delims=" %%P in ('where mpvnet.exe') do if not defined MPV_PATH set "MPV_PATH=%%P"
)

REM 1c. Check common install locations
if not defined MPV_PATH if exist "%PF%\mpv\mpv.exe" set "MPV_PATH=%PF%\mpv\mpv.exe"
if not defined MPV_PATH if exist "%PF86%\mpv\mpv.exe" set "MPV_PATH=%PF86%\mpv\mpv.exe"
if not defined MPV_PATH if exist "%PF%\mpv.net\mpvnet.exe" set "MPV_PATH=%PF%\mpv.net\mpvnet.exe"
if not defined MPV_PATH if exist "%PF86%\mpv.net\mpvnet.exe" set "MPV_PATH=%PF86%\mpv.net\mpvnet.exe"
if not defined MPV_PATH if exist "%LAD%\Programs\mpv\mpv.exe" set "MPV_PATH=%LAD%\Programs\mpv\mpv.exe"
if not defined MPV_PATH if exist "%LAD%\mpv\mpv.exe" set "MPV_PATH=%LAD%\mpv\mpv.exe"
if not defined MPV_PATH if exist "%UP%\scoop\apps\mpv\current\mpv.exe" set "MPV_PATH=%UP%\scoop\apps\mpv\current\mpv.exe"
if not defined MPV_PATH if exist "C:\mpv\mpv.exe" set "MPV_PATH=C:\mpv\mpv.exe"

REM ================================================================
REM  STEP 2: Stop here if mpv isn't installed - do NOT touch Stremio
REM ================================================================
if not defined MPV_PATH (
    echo [ERROR] MPV was NOT found on this system.
    echo.
    echo         This script will NOT modify Stremio until mpv is installed.
    echo.
    echo         Recommended setup ^(gpu-next / libplacebo / d3d11va / Vulkan^):
    echo.
    echo         1. Download the mpv-winbuild ^(by zhongfly^) Windows build:
    echo              https://github.com/zhongfly/mpv-winbuild/releases
    echo            Grab the latest "mpv-x86_64-*.7z" asset.
    echo         2. Extract it to:   C:\mpv\
    echo            ^(so that C:\mpv\mpv.exe exists^)
    echo         3. ^(Recommended^) Apply the full tuned config suite - open
    echo            PowerShell and run:
    echo              $temp = "$env:TEMP\biraj-mpv-conf"
    echo              git clone --depth 1 https://github.com/Biraj2004/biraj-mpv-conf.git $temp
    echo              New-Item -ItemType Directory -Force -Path "$env:APPDATA\mpv"
    echo              Copy-Item "$temp\mpv.conf","$temp\input.conf","$temp\menu.conf" -Destination "$env:APPDATA\mpv\" -Force
    echo              Copy-Item "$temp\fonts","$temp\scripts","$temp\script-opts" -Destination "$env:APPDATA\mpv\" -Recurse -Force
    echo              Remove-Item -Recurse -Force $temp
    echo            ^(Full guide: https://github.com/Biraj2004/biraj-mpv-conf^)
    echo         4. Run this script again.
    echo.
    echo         Already have mpv somewhere else? Run this script again as:
    echo             Win_Setup_Stremio_To_Play_In_MPV.bat "C:\your\path\to\mpv.exe"
    echo.
    pause
    endlocal
    exit /b 1
)

echo [INFO] MPV Executable   : %MPV_PATH%
echo.

REM ================================================================
REM  STEP 3: Warn if Stremio is running (file could be locked)
REM ================================================================
tasklist /FI "IMAGENAME eq Stremio.exe" 2>nul | find /I "Stremio.exe" >nul
if not errorlevel 1 (
    echo =======================================================================================================
    echo  WARNING: Stremio is currently running.
    echo  Close it fully ^(including the system tray icon^) before continuing,
    echo  otherwise the file may be locked or changes may get overwritten when Stremio exits.
    echo =======================================================================================================
    echo.
    set "STREMIO_CONFIRM="
    set /p STREMIO_CONFIRM=Type Y to continue anyway, or N to cancel : 
    if /i not "!STREMIO_CONFIRM!"=="Y" if /i not "!STREMIO_CONFIRM!"=="YES" (
        echo.
        echo [CANCELLED] Setup cancelled to prevent file lock conflict. Exiting safely.
        echo.
        pause
        endlocal
        exit /b 0
    )
    echo.
)

REM ================================================================
REM  STEP 4: Launch PowerShell Engine to patch server.js
REM ================================================================
where powershell >nul 2>&1
if errorlevel 1 (
    echo [ERROR] PowerShell was not found on this system. Cannot continue.
    echo.
    pause
    endlocal
    exit /b 1
)

powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -EncodedCommand "JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwB0AG8AcAAnAAoAZgB1AG4AYwB0AGkAbwBuACAARgBpAG4AZAAtAFMAZQByAHYAZQByAEoAcwB7AAoAJABmAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4AQwBvAGwAbABlAGMAdABpAG8AbgBzAC4ARwBlAG4AZQByAGkAYwAuAEwAaQBzAHQAWwBzAHQAcgBpAG4AZwBdAAoAJABzAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgACcAUwB5AHMAdABlAG0ALgBDAG8AbABsAGUAYwB0AGkAbwBuAHMALgBHAGUAbgBlAHIAaQBjAC4ASABhAHMAaABTAGUAdABbAHMAdAByAGkAbgBnAF0AJwAgACgAWwBTAHkAcwB0AGUAbQAuAFMAdAByAGkAbgBnAEMAbwBtAHAAYQByAGUAcgBdADoAOgBPAHIAZABpAG4AYQBsAEkAZwBuAG8AcgBlAEMAYQBzAGUAKQAKACQAawA9AEAAKAAiACQAZQBuAHYAOgBMAE8AQwBBAEwAQQBQAFAARABBAFQAQQBcAFAAcgBvAGcAcgBhAG0AcwBcAEwATgBWAFwAUwB0AHIAZQBtAGkAbwAtADQAXABzAGUAcgB2AGUAcgAuAGoAcwAiACwAIgAkAGUAbgB2ADoATABPAEMAQQBMAEEAUABQAEQAQQBUAEEAXABQAHIAbwBnAHIAYQBtAHMAXABMAE4AVgBcAFMAdAByAGUAbQBpAG8AXABzAGUAcgB2AGUAcgAuAGoAcwAiACwAIgAkAGUAbgB2ADoATABPAEMAQQBMAEEAUABQAEQAQQBUAEEAXABQAHIAbwBnAHIAYQBtAHMAXABTAHQAcgBlAG0AaQBvAFwAcwBlAHIAdgBlAHIALgBqAHMAIgAsACIAJABlAG4AdgA6AEwATwBDAEEATABBAFAAUABEAEEAVABBAFwAUAByAG8AZwByAGEAbQBzAFwAUwB0AHIAZQBtAGkAbwAtADQAXABzAGUAcgB2AGUAcgAuAGoAcwAiACwAIgAkAGUAbgB2ADoAUAByAG8AZwByAGEAbQBGAGkAbABlAHMAXABTAHQAcgBlAG0AaQBvAFwAcwBlAHIAdgBlAHIALgBqAHMAIgAsACIAJABlAG4AdgA6AFAAcgBvAGcAcgBhAG0ARgBpAGwAZQBzAFwAUwB0AHIAZQBtAGkAbwAtADQAXABzAGUAcgB2AGUAcgAuAGoAcwAiACwAIgAkAHsAZQBuAHYAOgBQAHIAbwBnAHIAYQBtAEYAaQBsAGUAcwAoAHgAOAA2ACkAfQBcAFMAdAByAGUAbQBpAG8AXABzAGUAcgB2AGUAcgAuAGoAcwAiACwAIgAkAGUAbgB2ADoAQQBQAFAARABBAFQAQQBcAHMAdAByAGUAbQBpAG8AXABzAGUAcgB2AGUAcgAuAGoAcwAiACwAIgAkAGUAbgB2ADoATABPAEMAQQBMAEEAUABQAEQAQQBUAEEAXABzAHQAcgBlAG0AaQBvAFwAcwBlAHIAdgBlAHIALgBqAHMAIgApAAoAZgBvAHIAZQBhAGMAaAAoACQAcAAgAGkAbgAgACQAawApAHsAaQBmACgAJABwACAALQBhAG4AZAAoAFQAZQBzAHQALQBQAGEAdABoACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAHAAKQApAHsAJABmAGwAPQAoAFIAZQBzAG8AbAB2AGUALQBQAGEAdABoACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAHAAKQAuAFAAYQB0AGgAOwBpAGYAKAAkAHMALgBBAGQAZAAoACQAZgBsACkAKQB7ACQAZgAuAEEAZABkACgAJABmAGwAKQB9AH0AfQAKAGkAZgAoACQAZgAuAEMAbwB1AG4AdAAgAC0AZQBxACAAMAApAHsACgAkAHIAPQBAACgAIgAkAGUAbgB2ADoATABPAEMAQQBMAEEAUABQAEQAQQBUAEEAXABQAHIAbwBnAHIAYQBtAHMAIgAsACQAZQBuAHYAOgBQAHIAbwBnAHIAYQBtAEYAaQBsAGUAcwAsACQAewBlAG4AdgA6AFAAcgBvAGcAcgBhAG0ARgBpAGwAZQBzACgAeAA4ADYAKQB9ACkAfABXAGgAZQByAGUALQBPAGIAagBlAGMAdAB7ACQAXwAgAC0AYQBuAGQAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABfACkAfQAKAGYAbwByAGUAYQBjAGgAKAAkAHIAdAAgAGkAbgAgACQAcgApAHsARwBlAHQALQBDAGgAaQBsAGQASQB0AGUAbQAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJAByAHQAIAAtAFIAZQBjAHUAcgBzAGUAIAAtAEYAaQBsAGUAIAAtAEYAaQBsAHQAZQByACAAJwBzAGUAcgB2AGUAcgAuAGoAcwAnACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlAHwAVwBoAGUAcgBlAC0ATwBiAGoAZQBjAHQAewAkAF8ALgBGAHUAbABsAE4AYQBtAGUAIAAtAG0AYQB0AGMAaAAgACcAKAA/AGkAKQBcAFwAcwB0AHIAZQBtAGkAbwAnAH0AfABGAG8AcgBFAGEAYwBoAC0ATwBiAGoAZQBjAHQAewBpAGYAKAAkAHMALgBBAGQAZAAoACQAXwAuAEYAdQBsAGwATgBhAG0AZQApACkAewAkAGYALgBBAGQAZAAoACQAXwAuAEYAdQBsAGwATgBhAG0AZQApAH0AfQB9AAoAfQAKAHIAZQB0AHUAcgBuACAAJABmAC4AVABvAEEAcgByAGEAeQAoACkACgB9AAoAZgB1AG4AYwB0AGkAbwBuACAARgBpAG4AZAAtAE0AYQB0AGMAaABpAG4AZwBCAHIAYQBjAGUAKAAkAHQALAAkAG8AKQB7AAoAJABkAD0AMAA7ACQAaQBuAFMAdAByAD0AJABmAGEAbABzAGUAOwAkAHEAPQBbAGMAaABhAHIAXQAwADsAJABlAHMAYwA9ACQAZgBhAGwAcwBlAAoAZgBvAHIAKAAkAGkAPQAkAG8AOwAkAGkAIAAtAGwAdAAgACQAdAAuAEwAZQBuAGcAdABoADsAJABpACsAKwApAHsACgAkAGMAPQAkAHQAWwAkAGkAXQAKAGkAZgAoACQAaQBuAFMAdAByACkAewBpAGYAKAAkAGUAcwBjACkAewAkAGUAcwBjAD0AJABmAGEAbABzAGUAOwBjAG8AbgB0AGkAbgB1AGUAfQBpAGYAKAAkAGMAIAAtAGUAcQAgACcAXAAnACkAewAkAGUAcwBjAD0AJAB0AHIAdQBlADsAYwBvAG4AdABpAG4AdQBlAH0AaQBmACgAJABjACAALQBlAHEAIAAkAHEAKQB7ACQAaQBuAFMAdAByAD0AJABmAGEAbABzAGUAfQBjAG8AbgB0AGkAbgB1AGUAfQAKAGkAZgAoACQAYwAgAC0AZQBxACAAJwAiACcAIAAtAG8AcgAgACQAYwAgAC0AZQBxACAAIgAnACIAKQB7ACQAaQBuAFMAdAByAD0AJAB0AHIAdQBlADsAJABxAD0AJABjADsAYwBvAG4AdABpAG4AdQBlAH0ACgBpAGYAKAAkAGMAIAAtAGUAcQAgACcAewAnACkAewAkAGQAKwArAH0AZQBsAHMAZQBpAGYAKAAkAGMAIAAtAGUAcQAgACcAfQAnACkAewAkAGQALQAtADsAaQBmACgAJABkACAALQBlAHEAIAAwACkAewByAGUAdAB1AHIAbgAgACQAaQB9AH0ACgB9AAoAcgBlAHQAdQByAG4AIAAtADEACgB9AAoAZgB1AG4AYwB0AGkAbwBuACAAUwBwAGwAaQB0AC0AVABvAHAATABlAHYAZQBsAEUAbgB0AHIAaQBlAHMAKAAkAGIAKQB7AAoAJABlAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4AQwBvAGwAbABlAGMAdABpAG8AbgBzAC4ARwBlAG4AZQByAGkAYwAuAEwAaQBzAHQAWwBzAHQAcgBpAG4AZwBdADsAJABkADEAPQAwADsAJABkADIAPQAwADsAJABpAG4AUwB0AHIAPQAkAGYAYQBsAHMAZQA7ACQAcQA9AFsAYwBoAGEAcgBdADAAOwAkAGUAcwBjAD0AJABmAGEAbABzAGUAOwAkAHMAdAA9ADAACgBmAG8AcgAoACQAaQA9ADAAOwAkAGkAIAAtAGwAdAAgACQAYgAuAEwAZQBuAGcAdABoADsAJABpACsAKwApAHsACgAkAGMAPQAkAGIAWwAkAGkAXQAKAGkAZgAoACQAaQBuAFMAdAByACkAewBpAGYAKAAkAGUAcwBjACkAewAkAGUAcwBjAD0AJABmAGEAbABzAGUAOwBjAG8AbgB0AGkAbgB1AGUAfQBpAGYAKAAkAGMAIAAtAGUAcQAgACcAXAAnACkAewAkAGUAcwBjAD0AJAB0AHIAdQBlADsAYwBvAG4AdABpAG4AdQBlAH0AaQBmACgAJABjACAALQBlAHEAIAAkAHEAKQB7ACQAaQBuAFMAdAByAD0AJABmAGEAbABzAGUAfQBjAG8AbgB0AGkAbgB1AGUAfQAKAGkAZgAoACQAYwAgAC0AZQBxACAAJwAiACcAIAAtAG8AcgAgACQAYwAgAC0AZQBxACAAIgAnACIAKQB7ACQAaQBuAFMAdAByAD0AJAB0AHIAdQBlADsAJABxAD0AJABjADsAYwBvAG4AdABpAG4AdQBlAH0ACgBzAHcAaQB0AGMAaAAoACQAYwApAHsACgAnAHsAJwB7ACQAZAAxACsAKwB9ACcAfQAnAHsAJABkADEALQAtAH0AJwBbACcAewAkAGQAMgArACsAfQAnAF0AJwB7ACQAZAAyAC0ALQB9AAoAJwAsACcAewBpAGYAKAAkAGQAMQAgAC0AZQBxACAAMAAgAC0AYQBuAGQAIAAkAGQAMgAgAC0AZQBxACAAMAApAHsAJABzAGcAPQAkAGIALgBTAHUAYgBzAHQAcgBpAG4AZwAoACQAcwB0ACwAJABpAC0AJABzAHQAKQAuAFQAcgBpAG0ARQBuAGQAKAApAC4AVAByAGkAbQBTAHQAYQByAHQAKABbAGMAaABhAHIAWwBdAF0AIgBcAHIAXABuACIAKQA7AGkAZgAoACQAcwBnACkAewAkAGUALgBBAGQAZAAoACQAcwBnACkAfQA7ACQAcwB0AD0AJABpACsAMQB9AH0ACgB9AAoAfQAKAGkAZgAoACQAcwB0ACAALQBsAHQAIAAkAGIALgBMAGUAbgBnAHQAaAApAHsAJABzAGcAPQAkAGIALgBTAHUAYgBzAHQAcgBpAG4AZwAoACQAcwB0ACkALgBUAHIAaQBtAEUAbgBkACgAKQAuAFQAcgBpAG0AUwB0AGEAcgB0ACgAWwBjAGgAYQByAFsAXQBdACIAXAByAFwAbgAiACkAOwBpAGYAKAAkAHMAZwApAHsAJABlAC4AQQBkAGQAKAAkAHMAZwApAH0AfQAKAHIAZQB0AHUAcgBuACAAJABlAC4AVABvAEEAcgByAGEAeQAoACkACgB9AAoAZgB1AG4AYwB0AGkAbwBuACAARwBlAHQALQBFAG4AdAByAHkASwBlAHkAKAAkAGUAKQB7ACQAbQA9AFsAcgBlAGcAZQB4AF0AOgA6AE0AYQB0AGMAaAAoACQAZQAsACcAXgBcAHMAKgAoAFsAQQAtAFoAYQAtAHoAXQBbAEEALQBaAGEALQB6ADAALQA5AF0AKgApAFwAcwAqADoAJwApADsAaQBmACgAJABtAC4AUwB1AGMAYwBlAHMAcwApAHsAcgBlAHQAdQByAG4AIAAkAG0ALgBHAHIAbwB1AHAAcwBbADEAXQAuAFYAYQBsAHUAZQB9ADsAcgBlAHQAdQByAG4AIAAkAG4AdQBsAGwAfQAKAGYAdQBuAGMAdABpAG8AbgAgAE4AZQB3AC0ATQBwAHYARQBuAHQAcgB5AFQAZQB4AHQAKAAkAG0ALAAkAGUAaQAsACQAcABpACwAJABwAHQAaQAsACQAbABlACkAewAKACQAdwA9AE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEMAbwBsAGwAZQBjAHQAaQBvAG4AcwAuAEcAZQBuAGUAcgBpAGMALgBMAGkAcwB0AFsAcwB0AHIAaQBuAGcAXQAKAGkAZgAoACQAbQApAHsAJAB3AC4AQQBkAGQAKAAiACcAYAAiACIAKwAkAG0ALgBSAGUAcABsAGEAYwBlACgAJwBcACcALAAnAFwAXAAnACkAKwAiAGAAIgAnACIAKQB9AAoAZgBvAHIAZQBhAGMAaAAoACQAcAAgAGkAbgAgAEAAKAAnAEMAOgBcAFwAUAByAG8AZwByAGEAbQAgAEYAaQBsAGUAcwBcAFwAbQBwAHYAXABcAG0AcAB2AC4AZQB4AGUAJwAsACcAQwA6AFwAXABQAHIAbwBnAHIAYQBtACAARgBpAGwAZQBzACAAKAB4ADgANgApAFwAXABtAHAAdgBcAFwAbQBwAHYALgBlAHgAZQAnACwAJwBDADoAXABcAFAAcgBvAGcAcgBhAG0AIABGAGkAbABlAHMAXABcAG0AcAB2AC4AbgBlAHQAXABcAG0AcAB2AG4AZQB0AC4AZQB4AGUAJwAsACcAQwA6AFwAXABQAHIAbwBnAHIAYQBtACAARgBpAGwAZQBzACAAKAB4ADgANgApAFwAXABtAHAAdgAuAG4AZQB0AFwAXABtAHAAdgBuAGUAdAAuAGUAeABlACcALAAnAEMAOgBcAFwAbQBwAHYAXABcAG0AcAB2AC4AZQB4AGUAJwApACkAewAkAGUAbgA9ACIAJwBgACIAJABwAGAAIgAnACIAOwBpAGYAKAAtAG4AbwB0ACAAJAB3AC4AQwBvAG4AdABhAGkAbgBzACgAJABlAG4AKQApAHsAJAB3AC4AQQBkAGQAKAAkAGUAbgApAH0AfQAKACQAbAA9AE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEMAbwBsAGwAZQBjAHQAaQBvAG4AcwAuAEcAZQBuAGUAcgBpAGMALgBMAGkAcwB0AFsAcwB0AHIAaQBuAGcAXQAKACQAbAAuAEEAZABkACgAIgAkAHsAZQBpAH0AbQBwAHYAOgAgAHsAIgApAAoAJABsAC4AQQBkAGQAKAAiACQAewBwAGkAfQB0AGkAdABsAGUAOgAgAGAAIgBNAFAAVgBgACIALAAiACkACgAkAGwALgBBAGQAZAAoACIAJAB7AHAAaQB9AGEAcgBnAHMAOgAgAFsAIABgACIALQAtAG4AbwAtAHQAZQByAG0AaQBuAGEAbABgACIAIABdACwAIgApAAoAJABsAC4AQQBkAGQAKAAiACQAewBwAGkAfQBzAHUAYgBBAHIAZwA6ACAAYAAiAC0ALQBzAHUAYgAtAGYAaQBsAGUAPQBgACIALAAiACkACgAkAGwALgBBAGQAZAAoACIAJAB7AHAAaQB9AHQAaQBtAGUAQQByAGcAOgAgAGAAIgAtAC0AcwB0AGEAcgB0AD0AYAAiACwAIgApAAoAJABsAC4AQQBkAGQAKAAiACQAewBwAGkAfQBwAGwAYQB5AEEAcgBnADoAIABgACIAYAAiACwAIgApAAoAJABsAC4AQQBkAGQAKAAiACQAewBwAGkAfQBkAGEAcgB3AGkAbgA6ACAAewAiACkACgAkAGwALgBBAGQAZAAoACIAJAB7AHAAdABpAH0AcABhAHQAaAA6ACAAWwAgAGAAIgAvAHUAcwByAC8AbABvAGMAYQBsAC8AYgBpAG4ALwBtAHAAdgBgACIALAAgAGAAIgAvAG8AcAB0AC8AaABvAG0AZQBiAHIAZQB3AC8AYgBpAG4ALwBtAHAAdgBgACIALAAgAGAAIgAvAG8AcAB0AC8AbABvAGMAYQBsAC8AYgBpAG4ALwBtAHAAdgBgACIALAAgAGAAIgAvAHMAdwAvAGIAaQBuAC8AbQBwAHYAYAAiACwAIABgACIALwBBAHAAcABsAGkAYwBhAHQAaQBvAG4AcwAvAG0AcAB2AC4AYQBwAHAALwBDAG8AbgB0AGUAbgB0AHMALwBNAGEAYwBPAFMALwBtAHAAdgBgACIAIABdACIAKQAKACQAbAAuAEEAZABkACgAIgAkAHsAcABpAH0AfQAsACIAKQAKACQAbAAuAEEAZABkACgAIgAkAHsAcABpAH0AbABpAG4AdQB4ADoAIAB7ACIAKQAKACQAbAAuAEEAZABkACgAIgAkAHsAcAB0AGkAfQBwAGEAdABoADoAIABbACAAYAAiAC8AdQBzAHIALwBiAGkAbgAvAG0AcAB2AGAAIgAgAF0AIgApAAoAJABsAC4AQQBkAGQAKAAiACQAewBwAGkAfQB9ACwAIgApAAoAJABsAC4AQQBkAGQAKAAiACQAewBwAGkAfQB3AGkAbgAzADIAOgAgAHsAIgApAAoAJABsAC4AQQBkAGQAKAAiACQAewBwAHQAaQB9AHAAYQB0AGgAOgAgAFsAIAAkACgAJAB3ACAALQBqAG8AaQBuACAAJwAsACAAJwApACAAXQAiACkACgAkAGwALgBBAGQAZAAoACIAJAB7AHAAaQB9AH0AIgApAAoAJABsAC4AQQBkAGQAKAAiACQAewBlAGkAfQB9ACIAKQAKAHIAZQB0AHUAcgBuACAAKAAkAGwAIAAtAGoAbwBpAG4AIAAkAGwAZQApAAoAfQAKAGYAdQBuAGMAdABpAG8AbgAgAFUAcABkAGEAdABlAC0ATABhAHUAbgBjAGgATABvAGcAaQBjAFEAdQBvAHQAaQBuAGcAKAAkAGMAKQB7AAoAaQBmACgAJABjAC4AQwBvAG4AdABhAGkAbgBzACgAJwBwAGwAYQB5AGUAcgBCAGkAbgAgAD0AIAAvAF4AIgAuACoAIgAkAC8AJwApACkAewByAGUAdAB1AHIAbgAgACQAYwB9AAoAJABpAG0AcAA9AEAAJwAKAHYAYQByACAAcABsAGEAeQBlAHIAQgBpAG4AIAA9ACAALwBeACIALgAqACIAJAAvAC4AdABlAHMAdAAoAHAAbABhAHkAZQByAFAAYQB0AGgAcwBbADAAXQApACAAPwAgAHAAbABhAHkAZQByAFAAYQB0AGgAcwBbADAAXQAgADoAIAAnACIAJwAgACsAIABwAGwAYQB5AGUAcgBQAGEAdABoAHMAWwAwAF0AIAArACAAJwAiACcALAAgAHcAcgBhAHAAcABlAGQAUwByAGMAIAA9ACAAJwAiACcAIAArACAAcwByAGMAIAArACAAJwAiACcALAAgAHEAdQBvAHQAZQBWAGEAbAB1AGUAIAA9ACAAZgB1AG4AYwB0AGkAbwBuACgAdgBhAGwAdQBlACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAJwAiACcAIAArACAAdgBhAGwAdQBlAC4AcgBlAHAAbABhAGMAZQAoAC8AIgAvAGcAaQAsACAAJwBcACIAJwApACAAKwAgACcAIgAnADsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ALAAgAHMAdQBiAHMAQwBtAGQAIAA9ACAAcwB1AGIAcwBGAGkAbABlACAAJgAmACAAcABsAGEAeQBlAHIAcwBbAHAAbABhAHkAZQByAF0ALgBzAHUAYgBBAHIAZwAgACYAJgAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcwB1AGIAQQByAGcALgBsAGUAbgBnAHQAaAAgAD4AIAAwACAAPwAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcwB1AGIAQQByAGcAIAArACAAcQB1AG8AdABlAFYAYQBsAHUAZQAoAHMAdQBiAHMARgBpAGwAZQApACAAOgAgACIAIgAsACAAYQByAGcAcwBDAG0AZAAgAD0AIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAGEAcgBnAHMAIAAmACYAIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAGEAcgBnAHMALgBsAGUAbgBnAHQAaAAgAD4AIAAwACAAPwAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AYQByAGcAcwAuAGoAbwBpAG4AKAAiACAAIgApACAAOgAgACIAIgAsACAAdABpAG0AZQBTAGUAYwAgAD0AIABwAGEAcgBzAGUASQBuAHQAKAB0AGkAbQBlACAALwAgADEAZQAzACkALAAgAHQAaQBtAGUAQwBtAGQAIAA9ACAAcABsAGEAeQBlAHIAcwBbAHAAbABhAHkAZQByAF0ALgB0AGkAbQBlAEEAcgBnACAAJgAmACAAcABsAGEAeQBlAHIAcwBbAHAAbABhAHkAZQByAF0ALgB0AGkAbQBlAEEAcgBnAC4AbABlAG4AZwB0AGgAIAA+ACAAMAAgACYAJgAgACEAaQBzAE4AYQBOACgAdABpAG0AZQBTAGUAYwApACAAJgAmACAAdABpAG0AZQBTAGUAYwAgAD4AIAAwACAAPwAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AdABpAG0AZQBBAHIAZwAgACsAIAB0AGkAbQBlAFMAZQBjACAAOgAgACIAIgAsACAAcABsAGEAeQBDAG0AZAAgAD0AIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAHAAbABhAHkAQQByAGcAIAAmACYAIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAHAAbABhAHkAQQByAGcALgBsAGUAbgBnAHQAaAAgAD4AIAAwACAAPwAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcABsAGEAeQBBAHIAZwAgACsAIAB3AHIAYQBwAHAAZQBkAFMAcgBjACAAOgAgAHcAcgBhAHAAcABlAGQAUwByAGMALAAgAGYAdQBsAGwAQwBtAGQAIAA9ACAAWwBwAGwAYQB5AGUAcgBCAGkAbgAsACAAdABpAG0AZQBDAG0AZAAsACAAYQByAGcAcwBDAG0AZAAsACAAcwB1AGIAcwBDAG0AZAAsACAAcABsAGEAeQBDAG0AZABdAC4AZgBpAGwAdABlAHIAKABCAG8AbwBsAGUAYQBuACkALgBqAG8AaQBuACgAIgAgACIAKQA7AAoAJwBAAAoAJABvAGEAPQBAACcACgB2AGEAcgAgAHcAcgBhAHAAcABlAGQAUwByAGMAIAA9ACAAJwAiACcAIAArACAAcwByAGMAIAArACAAJwAiACcALAAgAHMAdQBiAHMAQwBtAGQAIAA9ACAAcwB1AGIAcwBGAGkAbABlACAAJgAmACAAcABsAGEAeQBlAHIAcwBbAHAAbABhAHkAZQByAF0ALgBzAHUAYgBBAHIAZwAgACYAJgAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcwB1AGIAQQByAGcALgBsAGUAbgBnAHQAaAAgAD4AIAAwACAAPwAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcwB1AGIAQQByAGcAIAArACAAcwB1AGIAcwBGAGkAbABlACAAOgAgACIAIgAsACAAYQByAGcAcwBDAG0AZAAgAD0AIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAGEAcgBnAHMAIAAmACYAIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAGEAcgBnAHMALgBsAGUAbgBnAHQAaAAgAD4AIAAwACAAPwAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AYQByAGcAcwAuAGoAbwBpAG4AKAAiACAAIgApACAAOgAgACIAIgAsACAAdABpAG0AZQBDAG0AZAAgAD0AIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAHQAaQBtAGUAQQByAGcAIAAmACYAIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAHQAaQBtAGUAQQByAGcALgBsAGUAbgBnAHQAaAAgAD4AIAAwACAAPwAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AdABpAG0AZQBBAHIAZwAgACsAIABwAGEAcgBzAGUASQBuAHQAKAB0AGkAbQBlACAALwAgADEAZQAzACkAIAA6ACAAIgAiACwAIABwAGwAYQB5AEMAbQBkACAAPQAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcABsAGEAeQBBAHIAZwAgACYAJgAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcABsAGEAeQBBAHIAZwAuAGwAZQBuAGcAdABoACAAPgAgADAAIAA/ACAAcABsAGEAeQBlAHIAcwBbAHAAbABhAHkAZQByAF0ALgBwAGwAYQB5AEEAcgBnACAAKwAgAHcAcgBhAHAAcABlAGQAUwByAGMAIAA6ACAAdwByAGEAcABwAGUAZABTAHIAYwAsACAAZgB1AGwAbABDAG0AZAAgAD0AIABwAGwAYQB5AGUAcgBQAGEAdABoAHMAWwAwAF0AIAArACAAIgAgACIAIAArACAAdABpAG0AZQBDAG0AZAAgACsAIAAiACAAIgAgACsAIABhAHIAZwBzAEMAbQBkACAAKwAgACIAIAAiACAAKwAgAHMAdQBiAHMAQwBtAGQAIAArACAAIgAgACIAIAArACAAcABsAGEAeQBDAG0AZAA7AAoAJwBAAAoAJABvAGIAPQBAACcACgB2AGEAcgAgAHcAcgBhAHAAcABlAGQAUwByAGMAIAA9ACAAJwAiACcAIAArACAAcwByAGMAIAArACAAJwAiACcALAAgAHEAdQBvAHQAZQBWAGEAbAB1AGUAIAA9ACAAZgB1AG4AYwB0AGkAbwBuACgAdgBhAGwAdQBlACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAJwAiACcAIAArACAAdgBhAGwAdQBlAC4AcgBlAHAAbABhAGMAZQAoAC8AIgAvAGcAaQAsACAAJwBcACIAJwApACAAKwAgACcAIgAnADsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ALAAgAHMAdQBiAHMAQwBtAGQAIAA9ACAAcwB1AGIAcwBGAGkAbABlACAAJgAmACAAcABsAGEAeQBlAHIAcwBbAHAAbABhAHkAZQByAF0ALgBzAHUAYgBBAHIAZwAgACYAJgAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcwB1AGIAQQByAGcALgBsAGUAbgBnAHQAaAAgAD4AIAAwACAAPwAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcwB1AGIAQQByAGcAIAArACAAcQB1AG8AdABlAFYAYQBsAHUAZQAoAHMAdQBiAHMARgBpAGwAZQApACAAOgAgACIAIgAsACAAYQByAGcAcwBDAG0AZAAgAD0AIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAGEAcgBnAHMAIAAmACYAIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAGEAcgBnAHMALgBsAGUAbgBnAHQAaAAgAD4AIAAwACAAPwAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AYQByAGcAcwAuAGoAbwBpAG4AKAAiACAAIgApACAAOgAgACIAIgAsACAAdABpAG0AZQBDAG0AZAAgAD0AIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAHQAaQBtAGUAQQByAGcAIAAmACYAIABwAGwAYQB5AGUAcgBzAFsAcABsAGEAeQBlAHIAXQAuAHQAaQBtAGUAQQByAGcALgBsAGUAbgBnAHQAaAAgAD4AIAAwACAAPwAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AdABpAG0AZQBBAHIAZwAgACsAIABwAGEAcgBzAGUASQBuAHQAKAB0AGkAbQBlACAALwAgADEAZQAzACkAIAA6ACAAIgAiACwAIABwAGwAYQB5AEMAbQBkACAAPQAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcABsAGEAeQBBAHIAZwAgACYAJgAgAHAAbABhAHkAZQByAHMAWwBwAGwAYQB5AGUAcgBdAC4AcABsAGEAeQBBAHIAZwAuAGwAZQBuAGcAdABoACAAPgAgADAAIAA/ACAAcABsAGEAeQBlAHIAcwBbAHAAbABhAHkAZQByAF0ALgBwAGwAYQB5AEEAcgBnACAAKwAgAHcAcgBhAHAAcABlAGQAUwByAGMAIAA6ACAAdwByAGEAcABwAGUAZABTAHIAYwAsACAAZgB1AGwAbABDAG0AZAAgAD0AIABwAGwAYQB5AGUAcgBQAGEAdABoAHMAWwAwAF0AIAArACAAIgAgACIAIAArACAAdABpAG0AZQBDAG0AZAAgACsAIAAiACAAIgAgACsAIABhAHIAZwBzAEMAbQBkACAAKwAgACIAIAAiACAAKwAgAHMAdQBiAHMAQwBtAGQAIAArACAAIgAgACIAIAArACAAcABsAGEAeQBDAG0AZAA7AAoAJwBAAAoAaQBmACgAJABjAC4AQwBvAG4AdABhAGkAbgBzACgAJABvAGIAKQApAHsAcgBlAHQAdQByAG4AIAAkAGMALgBSAGUAcABsAGEAYwBlACgAJABvAGIALAAkAGkAbQBwACkAfQAKAGkAZgAoACQAYwAuAEMAbwBuAHQAYQBpAG4AcwAoACQAbwBhACkAKQB7AHIAZQB0AHUAcgBuACAAJABjAC4AUgBlAHAAbABhAGMAZQAoACQAbwBhACwAJABpAG0AcAApAH0ACgByAGUAdAB1AHIAbgAgACQAYwAKAH0ACgBmAHUAbgBjAHQAaQBvAG4AIABBAGQAZAAtAE0AcAB2AFQAbwBTAGUAcgB2AGUAcgBKAHMAKAAkAHAALAAkAG0AKQB7AAoAJAB1AD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAFUAVABGADgARQBuAGMAbwBkAGkAbgBnACgAJABmAGEAbABzAGUAKQAKACQAYwA9AFsAUwB5AHMAdABlAG0ALgBJAE8ALgBGAGkAbABlAF0AOgA6AFIAZQBhAGQAQQBsAGwAVABlAHgAdAAoACQAcAAsACQAdQApAAoAJABwAG0APQBbAHIAZQBnAGUAeABdADoAOgBNAGEAdABjAGgAKAAkAGMALAAnAHYAYQByAFwAcwArAHAAbABhAHkAZQByAHMAXABzACoAPQBcAHMAKgBcAHsAJwApAAoAaQBmACgALQBuAG8AdAAgACQAcABtAC4AUwB1AGMAYwBlAHMAcwApAHsAcgBlAHQAdQByAG4AIABbAHAAcwBjAHUAcwB0AG8AbQBvAGIAagBlAGMAdABdAEAAewBTAHQAYQB0AHUAcwA9ACcAVQBuAHMAdQBwAHAAbwByAHQAZQBkACcAOwBSAGUAYQBzAG8AbgA9ACcATgBvACAAIgBwAGwAYQB5AGUAcgBzACIAIABvAGIAagBlAGMAdAAgAGYAbwB1AG4AZAAuACcAfQB9AAoAJABvAGkAPQAkAGMALgBJAG4AZABlAHgATwBmACgAJwB7ACcALAAkAHAAbQAuAEkAbgBkAGUAeAApAAoAJABjAGkAPQBGAGkAbgBkAC0ATQBhAHQAYwBoAGkAbgBnAEIAcgBhAGMAZQAgACQAYwAgACQAbwBpAAoAaQBmACgAJABjAGkAIAAtAGwAdAAgADAAKQB7AHIAZQB0AHUAcgBuACAAWwBwAHMAYwB1AHMAdABvAG0AbwBiAGoAZQBjAHQAXQBAAHsAUwB0AGEAdAB1AHMAPQAnAFUAbgBzAHUAcABwAG8AcgB0AGUAZAAnADsAUgBlAGEAcwBvAG4APQAnAEMAbwB1AGwAZAAgAG4AbwB0ACAAZgBpAG4AZAAgAGUAbgBkACAAbwBmACAAcABsAGEAeQBlAHIAcwAgAG8AYgBqAGUAYwB0AC4AJwB9AH0ACgAkAGwAZQA9AGkAZgAoACQAYwAuAEMAbwBuAHQAYQBpAG4AcwAoACIAYAByAGAAbgAiACkAKQB7ACIAYAByAGAAbgAiAH0AZQBsAHMAZQB7ACIAYABuACIAfQAKACQAYgBzAD0AJABvAGkAKwAxADsAJABiAGQAPQAkAGMALgBTAHUAYgBzAHQAcgBpAG4AZwAoACQAYgBzACwAJABjAGkALQAkAGIAcwApAAoAJABpAG0APQBbAHIAZQBnAGUAeABdADoAOgBNAGEAdABjAGgAKAAkAGIAZAAsACcAKAA/AG0AKQBeACgAWwAgAFwAdABdACsAKQBbAEEALQBaAGEALQB6AF0AWwBBAC0AWgBhAC0AegAwAC0AOQBdACoAXABzACoAOgAnACkACgAkAGUAaQA9AGkAZgAoACQAaQBtAC4AUwB1AGMAYwBlAHMAcwApAHsAJABpAG0ALgBHAHIAbwB1AHAAcwBbADEAXQAuAFYAYQBsAHUAZQB9AGUAbABzAGUAewAnACAAIAAgACAAJwB9AAoAJABwAGkAPQAkAGUAaQArACcAIAAgACAAIAAnADsAJABwAHQAaQA9ACQAcABpACsAJwAgACAAIAAgACcACgAkAGIAaQA9AGkAZgAoACQAZQBpAC4ATABlAG4AZwB0AGgAIAAtAGcAZQAgADQAKQB7ACQAZQBpAC4AUwB1AGIAcwB0AHIAaQBuAGcAKAAwACwAJABlAGkALgBMAGUAbgBnAHQAaAAtADQAKQB9AGUAbABzAGUAewAnACcAfQAKACQAZQBuAHQAcgBpAGUAcwA9AEAAKABTAHAAbABpAHQALQBUAG8AcABMAGUAdgBlAGwARQBuAHQAcgBpAGUAcwAgACQAYgBkACkACgBpAGYAKAAtAG4AbwB0ACAAJABlAG4AdAByAGkAZQBzACAALQBvAHIAIAAkAGUAbgB0AHIAaQBlAHMALgBDAG8AdQBuAHQAIAAtAGUAcQAgADAAKQB7AHIAZQB0AHUAcgBuACAAWwBwAHMAYwB1AHMAdABvAG0AbwBiAGoAZQBjAHQAXQBAAHsAUwB0AGEAdAB1AHMAPQAnAFUAbgBzAHUAcABwAG8AcgB0AGUAZAAnADsAUgBlAGEAcwBvAG4APQAnAFAAbABhAHkAZQByAHMAIABvAGIAagBlAGMAdAAgAGkAcwAgAGUAbQBwAHQAeQAuACcAfQB9AAoAJABuAGUAdwBNAHAAdgA9AE4AZQB3AC0ATQBwAHYARQBuAHQAcgB5AFQAZQB4AHQAIAAkAG0AIAAkAGUAaQAgACQAcABpACAAJABwAHQAaQAgACQAbABlAAoAJAByAGIAPQBOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBDAG8AbABsAGUAYwB0AGkAbwBuAHMALgBHAGUAbgBlAHIAaQBjAC4ATABpAHMAdABbAHMAdAByAGkAbgBnAF0AOwAkAHIAZQBwAD0AJABmAGEAbABzAGUAOwAkAHYAaQA9AC0AMQAKAGYAbwByACgAJABpAD0AMAA7ACQAaQAgAC0AbAB0ACAAJABlAG4AdAByAGkAZQBzAC4AQwBvAHUAbgB0ADsAJABpACsAKwApAHsACgAkAGsAPQBHAGUAdAAtAEUAbgB0AHIAeQBLAGUAeQAgACQAZQBuAHQAcgBpAGUAcwBbACQAaQBdAAoAaQBmACgAJABrACAALQBlAHEAIAAnAHYAbABjACcAKQB7ACQAdgBpAD0AJAByAGIALgBDAG8AdQBuAHQAfQAKAGkAZgAoACQAawAgAC0AZQBxACAAJwBtAHAAdgAnACkAewAkAHIAYgAuAEEAZABkACgAJABuAGUAdwBNAHAAdgApADsAJAByAGUAcAA9ACQAdAByAHUAZQB9AGUAbABzAGUAewAkAHIAYgAuAEEAZABkACgAJABlAG4AdAByAGkAZQBzAFsAJABpAF0AKQB9AAoAfQAKAGkAZgAoAC0AbgBvAHQAIAAkAHIAZQBwACkAewBpAGYAKAAkAHYAaQAgAC0AZwBlACAAMAApAHsAJAByAGIALgBJAG4AcwBlAHIAdAAoACQAdgBpACsAMQAsACQAbgBlAHcATQBwAHYAKQB9AGUAbABzAGUAewAkAHIAYgAuAEEAZABkACgAJABuAGUAdwBNAHAAdgApAH0AfQAKACQAbgBiAD0AJABsAGUAKwAoACQAcgBiACAALQBqAG8AaQBuACAAKAAnACwAJwArACQAbABlACkAKQArACQAbABlACsAJABiAGkACgAkAG4AYwA9ACQAYwAuAFMAdQBiAHMAdAByAGkAbgBnACgAMAAsACQAYgBzACkAKwAkAG4AYgArACQAYwAuAFMAdQBiAHMAdAByAGkAbgBnACgAJABjAGkAKQAKACQAbgBjAD0AVQBwAGQAYQB0AGUALQBMAGEAdQBuAGMAaABMAG8AZwBpAGMAUQB1AG8AdABpAG4AZwAgACQAbgBjAAoAaQBmACgAJABuAGMAIAAtAGMAZQBxACAAJABjACkAewByAGUAdAB1AHIAbgAgAFsAcABzAGMAdQBzAHQAbwBtAG8AYgBqAGUAYwB0AF0AQAB7AFMAdABhAHQAdQBzAD0AJwBTAGsAaQBwAHAAZQBkACcAfQB9AAoAJAB0AHMAPQBHAGUAdAAtAEQAYQB0AGUAIAAtAEYAbwByAG0AYQB0ACAAJwB5AHkAeQB5AE0ATQBkAGQAXwBIAEgAbQBtAHMAcwAnADsAJABiAHAAPQAiACQAcAAuAGIAYQBjAGsAdQBwAF8AJAB0AHMAIgAKAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBGAGkAbABlAF0AOgA6AEMAbwBwAHkAKAAkAHAALAAkAGIAcAAsACQAdAByAHUAZQApAAoAWwBTAHkAcwB0AGUAbQAuAEkATwAuAEYAaQBsAGUAXQA6ADoAVwByAGkAdABlAEEAbABsAFQAZQB4AHQAKAAkAHAALAAkAG4AYwAsACQAdQApAAoAcgBlAHQAdQByAG4AIABbAHAAcwBjAHUAcwB0AG8AbQBvAGIAagBlAGMAdABdAEAAewBTAHQAYQB0AHUAcwA9ACcAUABhAHQAYwBoAGUAZAAnADsAQgBhAGMAawB1AHAAPQAkAGIAcAB9AAoAfQAKACQAbQBwAHYARQB4AGUAPQAkAGEAcgBnAHMAWwAwAF0ACgBpAGYAKAAtAG4AbwB0ACAAJABtAHAAdgBFAHgAZQApAHsACgAkAGMAZAA9AEAAKAAoAEcAZQB0AC0AQwBvAG0AbQBhAG4AZAAgACcAbQBwAHYALgBlAHgAZQAnACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlAHwAUwBlAGwAZQBjAHQALQBPAGIAagBlAGMAdAAgAC0ARQB4AHAAYQBuAGQAUAByAG8AcABlAHIAdAB5ACAAUwBvAHUAcgBjAGUAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAKQAsACgARwBlAHQALQBDAG8AbQBtAGEAbgBkACAAJwBtAHAAdgBuAGUAdAAuAGUAeABlACcAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAfABTAGUAbABlAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBFAHgAcABhAG4AZABQAHIAbwBwAGUAcgB0AHkAIABTAG8AdQByAGMAZQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQApACwAIgAkAGUAbgB2ADoAUAByAG8AZwByAGEAbQBGAGkAbABlAHMAXABtAHAAdgBcAG0AcAB2AC4AZQB4AGUAIgAsACIAJAB7AGUAbgB2ADoAUAByAG8AZwByAGEAbQBGAGkAbABlAHMAKAB4ADgANgApAH0AXABtAHAAdgBcAG0AcAB2AC4AZQB4AGUAIgAsACIAJABlAG4AdgA6AFAAcgBvAGcAcgBhAG0ARgBpAGwAZQBzAFwAbQBwAHYALgBuAGUAdABcAG0AcAB2AG4AZQB0AC4AZQB4AGUAIgAsACIAJAB7AGUAbgB2ADoAUAByAG8AZwByAGEAbQBGAGkAbABlAHMAKAB4ADgANgApAH0AXABtAHAAdgAuAG4AZQB0AFwAbQBwAHYAbgBlAHQALgBlAHgAZQAiACwAIgAkAGUAbgB2ADoATABPAEMAQQBMAEEAUABQAEQAQQBUAEEAXABQAHIAbwBnAHIAYQBtAHMAXABtAHAAdgBcAG0AcAB2AC4AZQB4AGUAIgAsACIAJABlAG4AdgA6AEwATwBDAEEATABBAFAAUABEAEEAVABBAFwAbQBwAHYAXABtAHAAdgAuAGUAeABlACIALAAiACQAZQBuAHYAOgBVAFMARQBSAFAAUgBPAEYASQBMAEUAXABzAGMAbwBvAHAAXABhAHAAcABzAFwAbQBwAHYAXABjAHUAcgByAGUAbgB0AFwAbQBwAHYALgBlAHgAZQAiACwAJwBDADoAXABtAHAAdgBcAG0AcAB2AC4AZQB4AGUAJwApAAoAZgBvAHIAZQBhAGMAaAAoACQAYwAgAGkAbgAgACQAYwBkACkAewBpAGYAKAAkAGMAIAAtAGEAbgBkACgAVABlAHMAdAAtAFAAYQB0AGgAIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQAYwApACkAewAkAG0AcAB2AEUAeABlAD0AJABjADsAYgByAGUAYQBrAH0AfQAKAH0ACgAkAHQAYQByAGcAZQB0AHMAPQBAACgARgBpAG4AZAAtAFMAZQByAHYAZQByAEoAcwApAAoAaQBmACgALQBuAG8AdAAgACQAdABhAHIAZwBlAHQAcwAgAC0AbwByACAAJAB0AGEAcgBnAGUAdABzAC4AQwBvAHUAbgB0ACAALQBlAHEAIAAwACkAewAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnAFsARQBSAFIATwBSAF0AIAAgACAAQwBvAHUAbABkACAAbgBvAHQAIABsAG8AYwBhAHQAZQAgAFMAdAByAGUAbQBpAG8AJwAnAHMAIABzAGUAcgB2AGUAcgAuAGoAcwAgAG8AbgAgAHQAaABpAHMAIABzAHkAcwB0AGUAbQAuACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAUgBlAGQACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwAgACAAIAAgACAAIAAgACAAIAAgAE0AYQBrAGUAIABzAHUAcgBlACAAUwB0AHIAZQBtAGkAbwAgAGkAcwAgAGkAbgBzAHQAYQBsAGwAZQBkACwAIAB0AGgAZQBuACAAdAByAHkAIABhAGcAYQBpAG4ALgAnACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAFkAZQBsAGwAbwB3AAoAZQB4AGkAdAAgADEACgB9AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACgAIgBbAEkATgBGAE8AXQAgACAAIAAgAEYAbwB1AG4AZAAgAHsAMAB9ACAAUwB0AHIAZQBtAGkAbwAgAGkAbgBzAHQAYQBsAGwAYQB0AGkAbwBuACgAcwApADoAIgAgAC0AZgAgACQAdABhAHIAZwBlAHQAcwAuAEMAbwB1AG4AdAApACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAFcAaABpAHQAZQAKAGYAbwByACgAJABpAD0AMAA7ACQAaQAgAC0AbAB0ACAAJAB0AGEAcgBnAGUAdABzAC4AQwBvAHUAbgB0ADsAJABpACsAKwApAHsAVwByAGkAdABlAC0ASABvAHMAdAAgACgAIgAgACAAWwB7ADAAfQBdACAAewAxAH0AIgAgAC0AZgAgACgAJABpACsAMQApACwAJAB0AGEAcgBnAGUAdABzAFsAJABpAF0AKQAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABXAGgAaQB0AGUAfQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgAkAHAAYwA9ADAAOwAkAHMAYwA9ADAAOwAkAGYAYwA9ADAACgBmAG8AcgBlAGEAYwBoACgAJAB0AGcAIABpAG4AIAAkAHQAYQByAGcAZQB0AHMAKQB7AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAnACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBhAHkACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAFAAUgBPAEMARQBTAFMASQBOAEcAXQAgAFQAYQByAGcAZQB0ADoAIAAkAHQAZwAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEMAeQBhAG4ACgB0AHIAeQB7AAoAJAByAGUAcwA9AEEAZABkAC0ATQBwAHYAVABvAFMAZQByAHYAZQByAEoAcwAgACQAdABnACAAJABtAHAAdgBFAHgAZQAKAHMAdwBpAHQAYwBoACgAJAByAGUAcwAuAFMAdABhAHQAdQBzACkAewAKACcAUABhAHQAYwBoAGUAZAAnAHsAJABwAGMAKwArADsAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBTAFUAQwBDAEUAUwBTAF0AIABCAGEAYwBrAHUAcAAgAGMAcgBlAGEAdABlAGQAOgAgACQAKAAkAHIAZQBzAC4AQgBhAGMAawB1AHAAKQAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgA7AFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnAFsAUwBVAEMAQwBFAFMAUwBdACAAbQBwAHYAIABwAGwAYQB5AGUAcgAgAGUAbgB0AHIAeQAgAGEAZABkAGUAZAAvAHUAcABkAGEAdABlAGQAIABzAHUAYwBjAGUAcwBzAGYAdQBsAGwAeQAuACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAH0ACgAnAFMAawBpAHAAcABlAGQAJwB7ACQAcwBjACsAKwA7AFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnAFsAUwBLAEkAUABdACAAIAAgACAAQQBsAHIAZQBhAGQAeQAgAGMAbwBuAGYAaQBnAHUAcgBlAGQAIABhAG4AZAAgAHUAcAAgAHQAbwAgAGQAYQB0AGUAIAAtACAAbgBvACAAYwBoAGEAbgBnAGUAcwAgAHIAZQBxAHUAaQByAGUAZAAuACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARABhAHIAawBHAHIAYQB5AH0ACgAnAFUAbgBzAHUAcABwAG8AcgB0AGUAZAAnAHsAJABmAGMAKwArADsAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBXAEEAUgBOAF0AIAAgACAAIAAkACgAJAByAGUAcwAuAFIAZQBhAHMAbwBuACkAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABZAGUAbABsAG8AdwB9AAoAfQAKAH0AYwBhAHQAYwBoAHsAJABmAGMAKwArADsAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBFAFIAUgBPAFIAXQAgACAAIAAkACgAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBNAGUAcwBzAGEAZwBlACkAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABSAGUAZAB9AAoAfQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGEAeQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACIAWwBTAFUATQBNAEEAUgBZAF0AIABQAGEAdABjAGgAZQBkACAAIAAgACAAIAAgACAAOgAgAHsAMAB9ACIAIAAtAGYAIAAkAHAAYwApACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACIAWwBTAFUATQBNAEEAUgBZAF0AIABBAGwAcgBlAGEAZAB5ACAATwBLACAAIAAgACAAOgAgAHsAMAB9ACIAIAAtAGYAIAAkAHMAYwApACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACIAWwBTAFUATQBNAEEAUgBZAF0AIABGAGEAaQBsAGUAZAAvAFcAYQByAG4AZQBkACAAOgAgAHsAMAB9ACIAIAAtAGYAIAAkAGYAYwApACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgACQAKABpAGYAKAAkAGYAYwAgAC0AZwB0ACAAMAApAHsAJwBZAGUAbABsAG8AdwAnAH0AZQBsAHMAZQB7ACcARwByAGUAZQBuACcAfQApAAoAaQBmACgAJABmAGMAIAAtAGUAcQAgADAAIAAtAG8AcgAgACQAcABjACAALQBnAHQAIAAwACkAewBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwBbAFMAVQBDAEMARQBTAFMAXQAgAFMAdAByAGUAbQBpAG8AIABNAFAAVgAgAHAAYQB0AGMAaABpAG4AZwAgAGMAbwBtAHAAbABlAHQAZQBkACEAJwAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4AfQBlAGwAcwBlAHsAVwByAGkAdABlAC0ASABvAHMAdAAgACcAWwBFAFIAUgBPAFIAXQAgACAAIABTAHQAcgBlAG0AaQBvACAATQBQAFYAIABwAGEAdABjAGgAaQBuAGcAIABjAG8AdQBsAGQAIABuAG8AdAAgAGIAZQAgAGEAcABwAGwAaQBlAGQALgAnACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAFIAZQBkAH0ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9ACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGEAeQAKAGkAZgAoACQAZgBjACAALQBnAHQAIAAwACAALQBhAG4AZAAgACQAcABjACAALQBlAHEAIAAwACkAewBlAHgAaQB0ACAAMQB9AAoAZQB4AGkAdAAgADAACgA=" 
set "PS_EXIT=!ERRORLEVEL!"

echo.
if "!PS_EXIT!"=="0" (
    echo -------------------------------------------------------------------------------------------------------
    echo =======================================================================================================
    echo [SUCCESS] Stremio MPV setup completed successfully.
    echo           Restart Stremio - "Play in MPV" should now appear next to "Play in VLC".
    echo =======================================================================================================
) else (
    echo -------------------------------------------------------------------------------------------------------
    echo =======================================================================================================
    echo [ERROR] Setup did not complete successfully. See messages above.
    echo =======================================================================================================
)

echo -------------------------------------------------------------------------------------------------------
echo =======================================================================================================
echo [FINISHED] Script execution finished. GitHub: https://github.com/Biraj2004
echo =======================================================================================================
echo.
pause
endlocal
exit /b !PS_EXIT!
