# Thumbfast configuration
# Centralized thumbnail scratch buffer in common cache directory
thumbnail=~~cache/thumbnails/thumbfast.out
quit_after_inactivity=30
tone_mapping=auto
hwdec=no
spawn_first=no
direct_io=yes
network=no